In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
#Creating an array
arr = np.array([1,2,3,4,5]) #1-D array
arr

array([1, 2, 3, 4, 5])

In [6]:
#Creating a 0-D array
arr0 = np.array(40)
arr0
print(arr0) #To print only elements

40


In [8]:
arr.ndim  #ndim is used to check dimension of the array
#arr0.ndim

1

In [10]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
print(arr.size) #Used to calculate size/no. of elements in an array
print(arr.nbytes) #Used to calculate total memory consumed by an array

5
20


In [12]:
#Single element size
arr2.itemsize

4

In [13]:
#for the data type of array
arr2.dtype

dtype('int32')

In [14]:
#for the specific element of the array
arr2[0,3]

4

In [15]:
#for specific row of the array
arr2[1]

array([5, 6, 7, 8])

In [18]:
arr2[1,:]

array([5, 6, 7, 8])

In [19]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
print(arr3[0:3])  #Slicing
print(arr3[5:])

[1 2 3]
[ 6  7  8  9 10]


In [26]:
print(arr2)
print(arr2[1,1:4])

[[1 2 3 4]
 [5 6 7 8]]
[6 7 8]


In [27]:
#copying an array
arr4 = arr2.copy()
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
#Zero matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
#All 1 matrix
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [30]:
#other matrix
np.full((10,5),22)

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [31]:
#importing random
from numpy import random

In [32]:
x = random.randint(100)
print(x)

50


In [34]:
np.random.rand(2,4)

array([[0.18842763, 0.11669015, 0.6681116 , 0.13468039],
       [0.70044533, 0.19013046, 0.60819065, 0.8517352 ]])

In [35]:
 #Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#Mathematical operation of an array
arrM = np.array([10,20,30,40,50])
print(arrM)

[10 20 30 40 50]


In [42]:
#Operation on an array
print(arrM+15)
print(arrM - 5)
print(arrM * 3)
print(arrM // 2)

[25 35 45 55 65]
[ 5 15 25 35 45]
[ 30  60  90 120 150]
[ 5 10 15 20 25]


In [43]:
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])


In [44]:
a1 + a2

array([11, 22, 33])

In [45]:
#To calculate cosine
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [46]:
#To calculate min,max,sum element of an array
print(np.min(arr3))
print(np.max(arr3))
print(np.sum(arr3))

1
10
55


In [47]:
#Iteration in an array
#In 1D array
for i in a1:
    print(i)

1
2
3


In [49]:
#In 2D array
for j in arr2:
    print(j)

[1 2 3 4]
[5 6 7 8]


In [50]:
for a in arr2:
    for b in a:
        print(b)

1
2
3
4
5
6
7
8
